### ISSUE TITLE
Doesn't work without SD card

### ISSUE THREAD

**Issue by jpqy** [ApacheThunder/NTR_Launcher#1]
First of all thanks for making this utility as it is the only thing that makes my supercard work. However, I found out that this utility requires an sdcard (even a blank one) to be inserted, otherwise I get a white screen and don't get the splash screen. Upon inserting a blank sdcard, it works again. Any idea why this is?

**Comment by ApacheThunder** [comment]
It expects there to be a INI file on SD. Specifically this:

https://github.com/ApacheThunder/NTR_Launcher/blob/master/nds/ntr_launcher.ini

It should be located in a folder titled "nds" on the root of your SD card. It uses this to configure various features. I suggest you create the file so that you can control which features you want. ;)

**Comment by NightScript370** [comment]
Why don't you make it, so that if there is no SD, it goes onto CTRNAND?

**Comment by ApacheThunder** [comment]
Uhh no. TWL mode doesn't have easy access to the ctrnand partition. Technically it does, but would require a lot of coding to work around the encryption of CTR_NAND which libnds does not provide anything for. So definitely not and there are no plans for that. Not only that there is no way to retrieve the needed encryption keys for CTR_NAND from TWL mode, so the user would have to manually provide those via a bootrom/otp dump. I suppose it could use space at the end of the nand for raw file system access. But this is dangerous as it could interfere with non standard NCSD layouts....So yeah not practical.

NTR_Launcher should just use default values with fat init fails. but hanging when no SD card is present...sounds like an issue with libnds. homebrew doesn't normally expect to run in TWL mode with SD access but with no SD inserted as it's not normally possible to boot them without an SD card. devkitarm/libnds doesn't fully support homebrew as DSiWare CIAs yet. hbmenu has a bootstrap CIA officially released, but it just boots hbmenu SRL from SD. So if no SD, it obviously doesn't get very far. So homebrew boots expecting there to be an SD card inserted due to hardcoded assumptions in libnds I would assume. I'm not gonna attempt fiddling around with libnds.

 Not much I can really do about that.

Instead you should think about checking how other homebrew behaves when installed as CIAs. Do they properly display the fat init failed error when you boot them without an SD card inserted? Like hbmenu for example. NOT the bootstrap CIA though. You have to take the boot.nds and use that as the CIA.

EDIT: I just tested my direct installs of hbmenu CIAs. They also hang without showing the fat init failed error if no SD card is present. This is confirmed a libnds/libfat issue. So please open a related issue on libnds/libfat github as this is not a NTR_Launcher related problem. Issue closed as this involves a issue with the devkitarm toolchain and not NTR_Launcher.
