### ISSUE TITLE
Default branch doesn't compile under latest libnds and makerom

### ISSUE THREAD

**Issue by Daeymon** [ApacheThunder/NTR_Launcher#5]
Subject says it all. I'm unable to compile this under the latest devkitPro and libnds.

Did a bit of amateur hour debugging, adding a bunch of "wno" error suppressors in the MakeFiles, setting Python to Python2 and updating the REG_CARD_ references. But even though the nds compiles and patches, its fails during the CIA creation. It ends on a "[SETTING ERROR] Argument "-rsf" is required" from makerom (latest version).

**Comment by ApacheThunder** [comment]
CIA file creation failing likely due to SRL (NDS file) not having a TWL Extended Header or something else wrong with SRL file.

I don't remember if I had to make manual edits to the SRL after compiling it. If that is the case then that is probably why a CIA won't build from it. Don't attempt to use the DSi branch on 3DS. Pretty sure it's not compatible or may have issues. Never tested that branch on 3DS.

As for compile issues on latest libnds. I will fix this if/when better cart reading code becomes available. At the moment NTR_Launcher can't read TWL carts (DSi Enhanced games/DSi Exclusive games) due to having to rely on ancient cart reading code from nitrohax. Don't really plan to revisit this project unless something new regarding the cart loading code becomes available. :(

**Comment by Daeymon** [comment]
I gave it a go compiling your dsi branch, and then ran it through the latest makerom without passing it through "patch_ndsheader_dsiware.py", and that one compiles fine and the final cia installed and ran fine (obviously no splash). So looks like you've already done the work.

**Comment by ApacheThunder** [comment]
Ahh good to hear. Seems missing splash is only thing you miss using it on 3DS (since DSi already had the splash. No point repeating it. :P )

**Comment by ApacheThunder** [comment]
I plan to retire the old 3DS branch and add/merge the DSi bootsplash with the DSi branch. The DSi branch I was able to merge Robz8's update that added TWL cart support so I will be making that one the default branch in the future. Since the DSi branch also works on DSi, it will be the only branch I will continue to maintain.
