### ISSUE TITLE
Latest version doesn't work

### ISSUE THREAD

**Issue by DraconicNEO** [ApacheThunder/NTR_Launcher#7]
The latest version of the software freezes at a black/white screen and it doesn't even say NTR Launcher, it says NDS Bootstrap. What is going on?

**Comment by ApacheThunder** [comment]
I've checked and banner is correct in makefile. I assume you are using this on 3DS? You may need to clear Home Menu's save data to clear out icon cache. YOu may have an old 3DS build of NTR Launcher installed? Or there is a conflict with nds-bootstrap which is a project I'm not currently involved with. I'll check if it does conflict and will ask them to change it if needed.

Otherwise it's just an issue with cached icon data on your 3DS console and is beyond my control. Uninstall any old builds, restart 3DS then install latest and see if that issue goes away.

EDIT: Ok checked and they have different game codes (and thus different titleids) so no idea why it would show you the wrong icon/banner.

**Comment by lifehackerhansol** [comment]
Due to some recent feedback from various members I have decided to test two versions of NTR Launcher on a completely formatted SD card. One being 2.5 (latest release at the time of writing), and the other being 2.3.

The results are as follows:
![IMG_1820](https://user-images.githubusercontent.com/37358975/125425946-24170180-2a7a-43a1-a612-cfe530d6246d.JPG)
![IMG_1819](https://user-images.githubusercontent.com/37358975/125425957-dcad0c30-09d7-4d9a-a426-3f34bea4a561.JPG)

NTR BOOTSTRAP is what appeared when I installed 2.5. 

NTR Launcher is what appeared when I installed 2.3. This was specifically installed after 2.5, so that there are no conflicts.

So far, I have only tested 3 flashcarts, the original R4, EZ-Flash 5, and an Acekard 2.1. All three that has historically worked with old NTR Launcher revisions. None of them work on 2.5. All of them work on 2.3.

I don't think this is an issue on DSi, but I am getting to testing that soon. It is pretty clear however that something is quite off about the new release.

Note: I have recompiled the DSi binary from source and ran make_cia on it. That worked. So it's not a source code problem.

**Comment by lifehackerhansol** [comment]
Update. I have tested it on the DSi. The exact same problem happens here.

![IMG_1821](https://user-images.githubusercontent.com/37358975/125430875-7d0c37c6-072c-49d7-97ee-68c731159c92.JPG)
![IMG_1822](https://user-images.githubusercontent.com/37358975/125430872-8acd09e9-4933-49b8-a84f-91ad36f72dbb.JPG)

The exact same issues as above happen. So it's not actually just the 3DS having problems. The DSi does too.

Something _really_ went wrong with that last release.

I must stress again that a recompile from source has no issues and has all the features that are mentioned in the release notes.

**Comment by DraconicNEO** [comment]
> 
> 
> I've checked and banner is correct in makefile. I assume you are using this on 3DS? You may need to clear Home Menu's save data to clear out icon cache. YOu may have an old 3DS build of NTR Launcher installed? Or there is a conflict with nds-bootstrap which is a project I'm not currently involved with. I'll check if it does conflict and will ask them to change it if needed.
> 
> Otherwise it's just an issue with cached icon data on your 3DS console and is beyond my control. Uninstall any old builds, restart 3DS then install latest and see if that issue goes away.
> 
> EDIT: Ok checked and they have different game codes (and thus different titleids) so no idea why it would show you the wrong icon/banner.

As @lifehackerhansol said there seems to be some sort of issue where version 2.5 is actually an NDS Bootstrap, the latest version that is still actually NTR Launcher appears to be version 2.3 I don't know how exactly that happened though, maybe you might want to look back through the history of your code.

**Comment by DraconicNEO** [comment]
I Just Installed version 2.3 and now I'm getting a different issue, anything I try to boot hangs on a white screen.

**Comment by lifehackerhansol** [comment]
I should note I didn't actually test 2.4. I just tested 2.3 because, uh, reasons.

**Comment by DraconicNEO** [comment]
> I should note I didn't actually test 2.4. I just tested 2.3 because, uh, reasons. 

Are you testing on an old 3DS or a new 3DS? I tried on a new 3DS and it just white screens.

**Comment by lifehackerhansol** [comment]
O3DS.

I could test 2.4, if you want. Though 2.4 had some quirks with certain carts that I don't exactly remember which. Not a big deal. The problem at hand is that 2.5 is not working yet does via a build from source.

**Comment by DraconicNEO** [comment]
> 
> 
> O3DS.
> 
> I could test 2.4, if you want. Though 2.4 had some quirks with certain carts that I don't exactly remember which. Not a big deal. The problem at hand is that 2.5 is not working yet does via a build from source.

Ah, I tried 2.3 on a new 3DS and it just gives a White screen and doesn't boot. Do you think it May not be compatible with the New 3DS revisions?

**Comment by scvgoodtogo** [comment]
> I must stress again that a recompile from source has no issues and has all the features that are mentioned in the release notes.

Do you mind sharing your recompiled cia with me? Been trying to boot my OG R4 without any luck with 2.5.

**Comment by DraconicNEO** [comment]
> 
> 
> > I must stress again that a recompile from source has no issues and has all the features that are mentioned in the release notes.
> 
> Do you mind sharing your recompiled cia with me? Been trying to boot my OG R4 without any luck with 2.5.

@lifehackerhansol Could you also share your compiled version? I'm not able to launch with any of the versions listed here on my New 2DS XL.

**Comment by lifehackerhansol** [comment]
[NTR_Launcher.zip](https://github.com/ApacheThunder/NTR_Launcher/files/6904496/NTR_Launcher.zip)

DSi = use TMFH to install to hiyaCFW. 

3DS = .... pretty straightforward.

I just recompiled from source with the latest commit and I haven't tested. Use at own risk etc etc

**Comment by scvgoodtogo** [comment]
@lifehackerhansol Thanks for the files. Installed the CIA and now it runs my DS games from Slot 1. But somehow my OG R4 w/ Wood is still not booting.

Edit: Typo

**Comment by DraconicNEO** [comment]
> 
> 
> [NTR_Launcher.zip](https://github.com/ApacheThunder/NTR_Launcher/files/6904496/NTR_Launcher.zip)
> 
> DSi = use TMFH to install to hiyaCFW.
> 
> 3DS = .... pretty straightforward.
> 
> I just recompiled from source with the latest commit and I haven't tested. Use at own risk etc etc

What size SD card are you using?

**Comment by ApacheThunder** [comment]
LOL I am not sure how I put ntr bootstrap in that release.

Well 2.6 is out now and it can boot all 3 of my current flash carts. (those being a M3 DS Real, original R4, and a DS-Xtreme)

Compatibility seems much improved over 2.5. I would ask ya'll retest. Will close this issue if the OP's results show improvement. :D

I'm not sure how I forgot about this for so long. :P

EDIT: Closing this issue since it's long sense been resolved.
